version: '3.9'

services:
  api:
    build: .
    ports:
      - "${APP_PORT}:8000"
    env_file:
      - .env
    depends_on:
      - db
      - mongo
    volumes:
      - ./:/app
    command: uvicorn app.main:app --host 0.0.0.0 --reload

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-gmao}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongo:
    image: mongo:6
    ports:
      - "${MONGODB_PORT:-27017}:27017"
    volumes:
      - mongodata:/data/db

volumes:
  pgdata:
  mongodata: